"""course updates

Revision ID: 0b7014b72e94
Revises: f4d5e6f7a8b9
Create Date: 2026-05-24 19:03:35.268030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa # noqa: F401
import sqlmodel # noqa: F401
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b7014b72e94'
down_revision: Union[str, None] = 'f4d5e6f7a8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courseprerequisite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('prerequisite_course_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('creation_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('update_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_course_id'], ['course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('auditlog')
    op.add_column('activity', sa.Column('points', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('chapter', sa.Column('due_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index(op.f('idx_chat_audit_log_action'), table_name='chat_audit_log')
    op.drop_index(op.f('idx_chat_audit_log_created_at'), table_name='chat_audit_log')
    op.drop_index(op.f('idx_chat_audit_log_org'), table_name='chat_audit_log')
    op.drop_index(op.f('idx_chat_audit_log_resource'), table_name='chat_audit_log')
    op.drop_index(op.f('idx_chat_audit_log_user'), table_name='chat_audit_log')
    op.drop_index(op.f('idx_chat_notification_message'), table_name='chat_notification')
    op.drop_index(op.f('idx_chat_notification_type'), table_name='chat_notification')
    op.drop_index(op.f('idx_chat_notification_unread'), table_name='chat_notification', postgresql_where='(is_read = false)')
    op.drop_index(op.f('idx_chat_notification_user'), table_name='chat_notification')
    op.drop_index(op.f('idx_conversation_archived'), table_name='conversation')
    op.drop_index(op.f('idx_conversation_last_message'), table_name='conversation')
    op.drop_index(op.f('idx_conversation_org_id'), table_name='conversation')
    op.drop_index(op.f('idx_conversation_participant_one'), table_name='conversation')
    op.drop_index(op.f('idx_conversation_participant_two'), table_name='conversation')
    op.drop_index(op.f('idx_participant_state_conversation'), table_name='conversation_participant_state')
    op.drop_index(op.f('idx_participant_state_typing'), table_name='conversation_participant_state')
    op.drop_index(op.f('idx_participant_state_user'), table_name='conversation_participant_state')
    op.drop_constraint(op.f('fk_discountcode_product_id_paymentsproduct'), 'discountcode', type_='foreignkey')
    op.drop_constraint(op.f('fk_discountcodeusage_product_id_paymentsproduct'), 'discountcodeusage', type_='foreignkey')
    op.drop_index(op.f('idx_message_conversation'), table_name='message')
    op.drop_index(op.f('idx_message_created_at'), table_name='message')
    op.drop_index(op.f('idx_message_deleted'), table_name='message')
    op.drop_index(op.f('idx_message_receiver'), table_name='message')
    op.drop_index(op.f('idx_message_sender'), table_name='message')
    op.drop_index(op.f('idx_message_type'), table_name='message')
    op.drop_index(op.f('idx_message_attachment_message'), table_name='message_attachment')
    op.drop_index(op.f('idx_message_attachment_org'), table_name='message_attachment')
    op.drop_index(op.f('idx_message_attachment_type'), table_name='message_attachment')
    op.drop_index(op.f('idx_message_edit_history_message'), table_name='message_edit_history')
    op.drop_index(op.f('idx_message_read_receipt_message'), table_name='message_read_receipt')
    op.drop_index(op.f('idx_message_read_receipt_read_at'), table_name='message_read_receipt', postgresql_where='(read_at IS NOT NULL)')
    op.drop_index(op.f('idx_message_read_receipt_user'), table_name='message_read_receipt')
    op.drop_constraint(op.f('paymentsuser_discount_code_id_fkey'), 'paymentsuser', type_='foreignkey')
    op.add_column('trailstep', sa.Column('points_earned', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('trailstep', sa.Column('is_late', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.sync_enum_values(
        enum_schema='public',
        enum_name='activitytypeenum',
        new_values=['TYPE_VIDEO', 'TYPE_DOCUMENT', 'TYPE_DYNAMIC', 'TYPE_ASSIGNMENT', 'TYPE_CUSTOM', 'TYPE_SMART_ARTICLE', 'TYPE_LIVE_SESSION', 'TYPE_ATTENDANCE'],
        affected_columns=[TableReference(table_schema='public', table_name='activity', column_name='activity_type')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='activitysubtypeenum',
        new_values=['SUBTYPE_DYNAMIC_PAGE', 'SUBTYPE_VIDEO_YOUTUBE', 'SUBTYPE_VIDEO_HOSTED', 'SUBTYPE_DOCUMENT_PDF', 'SUBTYPE_DOCUMENT_DOC', 'SUBTYPE_ASSIGNMENT_ANY', 'SUBTYPE_CUSTOM', 'SUBTYPE_SMART_ARTICLE_PDF', 'SUBTYPE_LIVE_JITSI', 'SUBTYPE_LIVE_HOSTED', 'SUBTYPE_ATTENDANCE_WEEKLY', 'SUBTYPE_ATTENDANCE_ONETIME'],
        affected_columns=[TableReference(table_schema='public', table_name='activity', column_name='activity_sub_type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='activitysubtypeenum',
        new_values=['SUBTYPE_DYNAMIC_PAGE', 'SUBTYPE_VIDEO_YOUTUBE', 'SUBTYPE_VIDEO_HOSTED', 'SUBTYPE_DOCUMENT_PDF', 'SUBTYPE_DOCUMENT_DOC', 'SUBTYPE_ASSIGNMENT_ANY', 'SUBTYPE_CUSTOM', 'SUBTYPE_SMART_ARTICLE_PDF', 'SUBTYPE_LIVE_JITSI', 'SUBTYPE_LIVE_HOSTED'],
        affected_columns=[TableReference(table_schema='public', table_name='activity', column_name='activity_sub_type')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='activitytypeenum',
        new_values=['TYPE_VIDEO', 'TYPE_DOCUMENT', 'TYPE_DYNAMIC', 'TYPE_ASSIGNMENT', 'TYPE_CUSTOM', 'TYPE_SMART_ARTICLE', 'TYPE_LIVE_SESSION'],
        affected_columns=[TableReference(table_schema='public', table_name='activity', column_name='activity_type')],
        enum_values_to_rename=[],
    )
    op.drop_column('trailstep', 'is_late')
    op.drop_column('trailstep', 'points_earned')
    op.create_foreign_key(op.f('paymentsuser_discount_code_id_fkey'), 'paymentsuser', 'discountcode', ['discount_code_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_message_read_receipt_user'), 'message_read_receipt', ['user_id'], unique=False)
    op.create_index(op.f('idx_message_read_receipt_read_at'), 'message_read_receipt', ['read_at'], unique=False, postgresql_where='(read_at IS NOT NULL)')
    op.create_index(op.f('idx_message_read_receipt_message'), 'message_read_receipt', ['message_id'], unique=False)
    op.create_index(op.f('idx_message_edit_history_message'), 'message_edit_history', ['message_id', sa.literal_column('edited_at DESC')], unique=False)
    op.create_index(op.f('idx_message_attachment_type'), 'message_attachment', ['file_type'], unique=False)
    op.create_index(op.f('idx_message_attachment_org'), 'message_attachment', ['org_id'], unique=False)
    op.create_index(op.f('idx_message_attachment_message'), 'message_attachment', ['message_id'], unique=False)
    op.create_index(op.f('idx_message_type'), 'message', ['message_type'], unique=False)
    op.create_index(op.f('idx_message_sender'), 'message', ['sender_id'], unique=False)
    op.create_index(op.f('idx_message_receiver'), 'message', ['receiver_id'], unique=False)
    op.create_index(op.f('idx_message_deleted'), 'message', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_message_created_at'), 'message', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_message_conversation'), 'message', ['conversation_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_foreign_key(op.f('fk_discountcodeusage_product_id_paymentsproduct'), 'discountcodeusage', 'paymentsproduct', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_discountcode_product_id_paymentsproduct'), 'discountcode', 'paymentsproduct', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_participant_state_user'), 'conversation_participant_state', ['user_id'], unique=False)
    op.create_index(op.f('idx_participant_state_typing'), 'conversation_participant_state', ['is_typing', 'typing_updated_at'], unique=False)
    op.create_index(op.f('idx_participant_state_conversation'), 'conversation_participant_state', ['conversation_id'], unique=False)
    op.create_index(op.f('idx_conversation_participant_two'), 'conversation', ['participant_two_id'], unique=False)
    op.create_index(op.f('idx_conversation_participant_one'), 'conversation', ['participant_one_id'], unique=False)
    op.create_index(op.f('idx_conversation_org_id'), 'conversation', ['org_id'], unique=False)
    op.create_index(op.f('idx_conversation_last_message'), 'conversation', [sa.literal_column('last_message_at DESC')], unique=False)
    op.create_index(op.f('idx_conversation_archived'), 'conversation', ['is_archived', 'org_id'], unique=False)
    op.create_index(op.f('idx_chat_notification_user'), 'chat_notification', ['user_id', 'is_read', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_chat_notification_unread'), 'chat_notification', ['user_id', 'is_read'], unique=False, postgresql_where='(is_read = false)')
    op.create_index(op.f('idx_chat_notification_type'), 'chat_notification', ['notification_type'], unique=False)
    op.create_index(op.f('idx_chat_notification_message'), 'chat_notification', ['message_id'], unique=False)
    op.create_index(op.f('idx_chat_audit_log_user'), 'chat_audit_log', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_chat_audit_log_resource'), 'chat_audit_log', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('idx_chat_audit_log_org'), 'chat_audit_log', ['org_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_chat_audit_log_created_at'), 'chat_audit_log', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_chat_audit_log_action'), 'chat_audit_log', ['action'], unique=False)
    op.drop_column('chapter', 'due_date')
    op.drop_column('activity', 'points')
    op.create_table('auditlog',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resource', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('auditlog_pkey'))
    )
    op.drop_table('courseprerequisite')
    # ### end Alembic commands ###
