"""Add verification OTP fields

Revision ID: 2b55f51ed868
Revises: e9f8a7b6c5d4
Create Date: 2026-08-11 05:29:35.575263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa # noqa: F401
import sqlmodel # noqa: F401
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b55f51ed868'
down_revision: Union[str, None] = 'e9f8a7b6c5d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auditlog')
    op.add_column('user', sa.Column('verification_otp', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('verification_otp_expiry', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.sync_enum_values(
        enum_schema='public',
        enum_name='paymentproviderenum',
        new_values=['flutterwave'],
        affected_columns=[TableReference(table_schema='public', table_name='payments_config', column_name='provider')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='paymentproviderenum',
        new_values=['paystack'],
        affected_columns=[TableReference(table_schema='public', table_name='payments_config', column_name='provider')],
        enum_values_to_rename=[],
    )
    op.drop_column('user', 'verification_otp_expiry')
    op.drop_column('user', 'verification_otp')
    op.create_table('auditlog',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resource', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('auditlog_pkey'))
    )
    # ### end Alembic commands ###
