"""Add organization_name to user

Revision ID: 344680c73fd1
Revises: 2b55f51ed868
Create Date: 2026-08-11 06:27:13.533369

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '344680c73fd1'
down_revision: str | None = '2b55f51ed868'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('organization_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'organization_name')
    # ### end Alembic commands ###
