"""add_referral_system_tables_and_user_fields

Revision ID: 667a4d49251f
Revises: 52b824c8811e
Create Date: 2026-02-21 15:15:53.224732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa # noqa: F401
import sqlmodel # noqa: F401
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '667a4d49251f'
down_revision: Union[str, None] = '52b824c8811e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('DISPOSABLE', 'LEGITIMATE', name='domainlisttype').create(op.get_bind())
    sa.Enum('REQUESTED', 'PROCESSING', 'COMPLETED', 'FAILED', name='payoutstatus').create(op.get_bind())
    sa.Enum('PENDING', 'ELIGIBLE', 'PAID', 'FORFEITED', 'PENDING_REVIEW', name='commissionstatus').create(op.get_bind())
    sa.Enum('ACTIVE', 'INACTIVE', name='referralcodestatus').create(op.get_bind())
    op.create_table('emaildomainlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('list_type', postgresql.ENUM('DISPOSABLE', 'LEGITIMATE', name='domainlisttype', create_type=False), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emaildomainlist_domain'), 'emaildomainlist', ['domain'], unique=False)
    op.create_index(op.f('ix_emaildomainlist_is_active'), 'emaildomainlist', ['is_active'], unique=False)
    op.create_index(op.f('ix_emaildomainlist_list_type'), 'emaildomainlist', ['list_type'], unique=False)
    op.create_table('payments_config',
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_specific_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider_config', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referralcode',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('referral_link', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', name='referralcodestatus', create_type=False), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('referrer_user_id', sa.BigInteger(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_referralcode_code', 'referralcode', ['code'], unique=False)
    op.create_index('idx_referralcode_link', 'referralcode', ['referral_link'], unique=False)
    op.create_index('idx_referralcode_referrer_org', 'referralcode', ['referrer_user_id', 'org_id'], unique=False)
    op.create_index(op.f('ix_referralcode_code'), 'referralcode', ['code'], unique=True)
    op.create_table('referrerpayoutrequest',
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('converted_amount', sa.Float(), nullable=True),
    sa.Column('status', postgresql.ENUM('REQUESTED', 'PROCESSING', 'COMPLETED', 'FAILED', name='payoutstatus', create_type=False), nullable=False),
    sa.Column('paystack_transfer_recipient_code', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('paystack_transfer_code', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('bank_account_info', sa.JSON(), nullable=True),
    sa.Column('request_date', sa.DateTime(), nullable=False),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('referrer_user_id', sa.BigInteger(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payoutrequest_org', 'referrerpayoutrequest', ['org_id'], unique=False)
    op.create_index('idx_payoutrequest_referrer_status', 'referrerpayoutrequest', ['referrer_user_id', 'status'], unique=False)
    op.create_table('referraltracking',
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('browser_fingerprint', sa.JSON(), nullable=True),
    sa.Column('registration_complete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referred_user_id', sa.BigInteger(), nullable=False),
    sa.Column('referral_code_id', sa.BigInteger(), nullable=False),
    sa.Column('referrer_user_id', sa.BigInteger(), nullable=False),
    sa.Column('signup_date', sa.DateTime(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['referral_code_id'], ['referralcode.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referred_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_referraltracking_code', 'referraltracking', ['referral_code_id'], unique=False)
    op.create_index('idx_referraltracking_device', 'referraltracking', ['device_id'], unique=False)
    op.create_index('idx_referraltracking_ip', 'referraltracking', ['ip_address'], unique=False)
    op.create_index('idx_referraltracking_referred', 'referraltracking', ['referred_user_id'], unique=False)
    op.create_index('idx_referraltracking_unique_user', 'referraltracking', ['referred_user_id'], unique=True)
    op.create_index(op.f('ix_referraltracking_device_id'), 'referraltracking', ['device_id'], unique=False)
    op.create_index(op.f('ix_referraltracking_ip_address'), 'referraltracking', ['ip_address'], unique=False)
    op.create_table('referralcommission',
    sa.Column('commission_amount', sa.Float(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ELIGIBLE', 'PAID', 'FORFEITED', 'PENDING_REVIEW', name='commissionstatus', create_type=False), nullable=False),
    sa.Column('payment_completion_date', sa.DateTime(), nullable=True),
    sa.Column('refund_period_expiration_date', sa.DateTime(), nullable=True),
    sa.Column('payout_date', sa.DateTime(), nullable=True),
    sa.Column('payout_request_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('referrer_user_id', sa.BigInteger(), nullable=False),
    sa.Column('referred_user_id', sa.BigInteger(), nullable=False),
    sa.Column('payment_user_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=True),
    sa.Column('referral_code_id', sa.BigInteger(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_user_id'], ['paymentsuser.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referral_code_id'], ['referralcode.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referred_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_referralcommission_org', 'referralcommission', ['org_id'], unique=False)
    op.create_index('idx_referralcommission_payment_user', 'referralcommission', ['payment_user_id'], unique=False)
    op.create_index('idx_referralcommission_referred', 'referralcommission', ['referred_user_id'], unique=False)
    op.create_index('idx_referralcommission_referrer_status', 'referralcommission', ['referrer_user_id', 'status'], unique=False)
    op.create_index('idx_referralcommission_unique', 'referralcommission', ['payment_user_id', 'referral_code_id'], unique=True)
    # op.drop_table('discount_code')  # Commented out - table is still in use
    # op.drop_table('auditlog')  # Commented out - table is still in use
    # op.drop_table('paymentsconfig')  # Commented out - table is still in use
    # op.drop_table('discount_code_usage')  # Commented out - table is still in use
    op.add_column('discountcode', sa.Column('course_id', sa.BigInteger(), nullable=True))
    op.alter_column('discountcode', 'org_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('discountcode', 'discount_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PERCENTAGE', 'FIXED', name='discounttypeenum'),
               existing_nullable=False,
               postgresql_using='discount_type::discounttypeenum')
    op.alter_column('discountcode', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(op.f('discountcode_org_id_fkey'), 'discountcode', type_='foreignkey')
    op.alter_column('discountcodeusage', 'discount_code_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('discountcodeusage', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('discountcodeusage', 'course_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('discountcodeusage', 'payment_user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('discountcodeusage', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_discountcodeusage_user_course_unique'), table_name='discountcodeusage')
    op.drop_constraint(op.f('discountcodeusage_user_id_fkey'), 'discountcodeusage', type_='foreignkey')
    op.drop_constraint(op.f('discountcodeusage_payment_user_id_fkey'), 'discountcodeusage', type_='foreignkey')
    op.drop_constraint(op.f('discountcodeusage_discount_code_id_fkey'), 'discountcodeusage', type_='foreignkey')
    op.drop_constraint(op.f('discountcodeusage_course_id_fkey'), 'discountcodeusage', type_='foreignkey')
    op.drop_constraint(op.f('paymentsproduct_payments_config_id_fkey'), 'paymentsproduct', type_='foreignkey')
    op.create_foreign_key(None, 'paymentsproduct', 'payments_config', ['payments_config_id'], ['id'], ondelete='CASCADE')
    op.add_column('paymentsuser', sa.Column('referral_code_id', sa.BigInteger(), nullable=True))
    op.drop_constraint(op.f('fk_paymentsuser_discount_code'), 'paymentsuser', type_='foreignkey')
    op.drop_constraint(op.f('fk_paymentsuser_discount_code_id'), 'paymentsuser', type_='foreignkey')
    op.add_column('user', sa.Column('referral_commission_balance', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('user', sa.Column('has_referral_code', sa.Boolean(), nullable=False, server_default='false'))
    op.drop_constraint(op.f('userorganization_user_id_fkey'), 'userorganization', type_='foreignkey')
    op.create_foreign_key(None, 'userorganization', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('waitlist_config', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_waitlist_config_launch_datetime'), table_name='waitlist_config')
    op.drop_index(op.f('ix_waitlist_config_org_status'), table_name='waitlist_config')
    op.drop_constraint(op.f('waitlist_config_waitlist_uuid_key'), 'waitlist_config', type_='unique')
    op.drop_index(op.f('ix_waitlist_config_waitlist_uuid'), table_name='waitlist_config')
    op.create_index(op.f('ix_waitlist_config_waitlist_uuid'), 'waitlist_config', ['waitlist_uuid'], unique=True)
    op.alter_column('waitlist_course_preference', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('waitlist_course_preference', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('waitlist_course_preference', 'waitlist_config_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('waitlist_course_preference', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_wcp_course_id'), table_name='waitlist_course_preference')
    op.drop_index(op.f('ix_wcp_unique'), table_name='waitlist_course_preference')
    op.drop_index(op.f('ix_wcp_user_id'), table_name='waitlist_course_preference')
    op.drop_index(op.f('ix_wcp_waitlist_config_id'), table_name='waitlist_course_preference')
    op.alter_column('waitlist_email_log', 'waitlist_config_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('waitlist_email_log', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_waitlist_email_log_status'), table_name='waitlist_email_log')
    op.drop_index(op.f('ix_waitlist_email_log_user_id'), table_name='waitlist_email_log')
    op.drop_index(op.f('ix_waitlist_email_log_waitlist_config_id'), table_name='waitlist_email_log')
    sa.Enum('ACTIVE', 'WAITLIST', 'WAITLIST_ACTIVATED', 'SUSPENDED', 'PENDING_VERIFICATION', name='userstatusenum').drop(op.get_bind())
    sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', 'SCHEDULED', name='waitliststatusenum').drop(op.get_bind())
    op.sync_enum_values(
        enum_schema='public',
        enum_name='discounttypeenum',
        new_values=['PERCENTAGE', 'FIXED'],
        affected_columns=[TableReference(table_schema='public', table_name='discountcode', column_name='discount_type')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='paymentproviderenum',
        new_values=['paystack'],
        affected_columns=[TableReference(table_schema='public', table_name='payments_config', column_name='provider')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='paymentproviderenum',
        new_values=['STRIPE'],
        affected_columns=[TableReference(table_schema='public', table_name='payments_config', column_name='provider')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='discounttypeenum',
        new_values=['percentage', 'fixed'],
        affected_columns=[TableReference(table_schema='public', table_name='discountcode', column_name='discount_type')],
        enum_values_to_rename=[],
    )
    sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', 'SCHEDULED', name='waitliststatusenum').create(op.get_bind())
    sa.Enum('ACTIVE', 'WAITLIST', 'WAITLIST_ACTIVATED', 'SUSPENDED', 'PENDING_VERIFICATION', name='userstatusenum').create(op.get_bind())
    op.create_index(op.f('ix_waitlist_email_log_waitlist_config_id'), 'waitlist_email_log', ['waitlist_config_id'], unique=False)
    op.create_index(op.f('ix_waitlist_email_log_user_id'), 'waitlist_email_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_waitlist_email_log_status'), 'waitlist_email_log', ['email_sent'], unique=False)
    op.alter_column('waitlist_email_log', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('waitlist_email_log', 'waitlist_config_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_wcp_waitlist_config_id'), 'waitlist_course_preference', ['waitlist_config_id'], unique=False)
    op.create_index(op.f('ix_wcp_user_id'), 'waitlist_course_preference', ['user_id'], unique=False)
    op.create_index(op.f('ix_wcp_unique'), 'waitlist_course_preference', ['user_id', 'course_id', 'waitlist_config_id'], unique=True)
    op.create_index(op.f('ix_wcp_course_id'), 'waitlist_course_preference', ['course_id'], unique=False)
    op.alter_column('waitlist_course_preference', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('waitlist_course_preference', 'waitlist_config_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('waitlist_course_preference', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('waitlist_course_preference', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_waitlist_config_waitlist_uuid'), table_name='waitlist_config')
    op.create_index(op.f('ix_waitlist_config_waitlist_uuid'), 'waitlist_config', ['waitlist_uuid'], unique=False)
    op.create_unique_constraint(op.f('waitlist_config_waitlist_uuid_key'), 'waitlist_config', ['waitlist_uuid'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_waitlist_config_org_status'), 'waitlist_config', ['org_id', 'status'], unique=False)
    op.create_index(op.f('ix_waitlist_config_launch_datetime'), 'waitlist_config', ['launch_datetime'], unique=False)
    op.alter_column('waitlist_config', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'userorganization', type_='foreignkey')
    op.create_foreign_key(op.f('userorganization_user_id_fkey'), 'userorganization', 'user', ['user_id'], ['id'])
    op.drop_column('user', 'has_referral_code')
    op.drop_column('user', 'referral_commission_balance')
    op.create_foreign_key(op.f('fk_paymentsuser_discount_code_id'), 'paymentsuser', 'discountcode', ['discount_code_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_paymentsuser_discount_code'), 'paymentsuser', 'discount_code', ['discount_code_id'], ['id'], ondelete='SET NULL')
    op.drop_column('paymentsuser', 'referral_code_id')
    op.drop_constraint(None, 'paymentsproduct', type_='foreignkey')
    op.create_foreign_key(op.f('paymentsproduct_payments_config_id_fkey'), 'paymentsproduct', 'paymentsconfig', ['payments_config_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('discountcodeusage_course_id_fkey'), 'discountcodeusage', 'course', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('discountcodeusage_discount_code_id_fkey'), 'discountcodeusage', 'discountcode', ['discount_code_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('discountcodeusage_payment_user_id_fkey'), 'discountcodeusage', 'paymentsuser', ['payment_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('discountcodeusage_user_id_fkey'), 'discountcodeusage', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_discountcodeusage_user_course_unique'), 'discountcodeusage', ['user_id', 'course_id', 'discount_code_id'], unique=True)
    op.alter_column('discountcodeusage', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('discountcodeusage', 'payment_user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('discountcodeusage', 'course_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('discountcodeusage', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('discountcodeusage', 'discount_code_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_foreign_key(op.f('discountcode_org_id_fkey'), 'discountcode', 'organization', ['org_id'], ['id'], ondelete='CASCADE')
    op.alter_column('discountcode', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('discountcode', 'discount_type',
               existing_type=sa.Enum('PERCENTAGE', 'FIXED', name='discounttypeenum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('discountcode', 'org_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('discountcode', 'course_id')
    op.create_table('discount_code_usage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('discount_code_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('payment_user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('original_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('discount_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('final_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('used_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('discount_code_usage_course_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['discount_code_id'], ['discount_code.id'], name=op.f('discount_code_usage_discount_code_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('discount_code_usage_org_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_user_id'], ['paymentsuser.id'], name=op.f('discount_code_usage_payment_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('discount_code_usage_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('discount_code_usage_pkey')),
    sa.UniqueConstraint('discount_code_id', 'user_id', 'course_id', name=op.f('uq_discount_code_usage'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('payment_user_id', name=op.f('uq_discount_code_usage_payment'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('paymentsconfig',
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('provider', postgresql.ENUM('STRIPE', name='paymentproviderenum', create_type=False), autoincrement=False, nullable=False),
    sa.Column('provider_specific_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('provider_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('creation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('update_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('paymentsconfig_org_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('paymentsconfig_pkey'))
    )
    op.create_table('auditlog',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resource', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('auditlog_pkey'))
    )
    op.create_table('discount_code',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('discount_type', postgresql.ENUM('percentage', 'fixed', name='discounttypeenum', create_type=False), autoincrement=False, nullable=False),
    sa.Column('discount_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('max_uses', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_uses', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('valid_from', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('valid_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('creation_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('discount_code_org_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('discount_code_pkey')),
    sa.UniqueConstraint('org_id', 'code', name=op.f('uq_discount_code_org_code'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index('idx_referralcommission_unique', table_name='referralcommission')
    op.drop_index('idx_referralcommission_referrer_status', table_name='referralcommission')
    op.drop_index('idx_referralcommission_referred', table_name='referralcommission')
    op.drop_index('idx_referralcommission_payment_user', table_name='referralcommission')
    op.drop_index('idx_referralcommission_org', table_name='referralcommission')
    op.drop_table('referralcommission')
    op.drop_index(op.f('ix_referraltracking_ip_address'), table_name='referraltracking')
    op.drop_index(op.f('ix_referraltracking_device_id'), table_name='referraltracking')
    op.drop_index('idx_referraltracking_unique_user', table_name='referraltracking')
    op.drop_index('idx_referraltracking_referred', table_name='referraltracking')
    op.drop_index('idx_referraltracking_ip', table_name='referraltracking')
    op.drop_index('idx_referraltracking_device', table_name='referraltracking')
    op.drop_index('idx_referraltracking_code', table_name='referraltracking')
    op.drop_table('referraltracking')
    op.drop_index('idx_payoutrequest_referrer_status', table_name='referrerpayoutrequest')
    op.drop_index('idx_payoutrequest_org', table_name='referrerpayoutrequest')
    op.drop_table('referrerpayoutrequest')
    op.drop_index(op.f('ix_referralcode_code'), table_name='referralcode')
    op.drop_index('idx_referralcode_referrer_org', table_name='referralcode')
    op.drop_index('idx_referralcode_link', table_name='referralcode')
    op.drop_index('idx_referralcode_code', table_name='referralcode')
    op.drop_table('referralcode')
    op.drop_table('payments_config')
    op.drop_index(op.f('ix_emaildomainlist_list_type'), table_name='emaildomainlist')
    op.drop_index(op.f('ix_emaildomainlist_is_active'), table_name='emaildomainlist')
    op.drop_index(op.f('ix_emaildomainlist_domain'), table_name='emaildomainlist')
    op.drop_table('emaildomainlist')
    sa.Enum('ACTIVE', 'INACTIVE', name='referralcodestatus').drop(op.get_bind())
    sa.Enum('PENDING', 'ELIGIBLE', 'PAID', 'FORFEITED', 'PENDING_REVIEW', name='commissionstatus').drop(op.get_bind())
    sa.Enum('REQUESTED', 'PROCESSING', 'COMPLETED', 'FAILED', name='payoutstatus').drop(op.get_bind())
    sa.Enum('DISPOSABLE', 'LEGITIMATE', name='domainlisttype').drop(op.get_bind())
    # ### end Alembic commands ###
