"""update_waitlist_course_preference_to_payments_product

Revision ID: 96d18768cf0b
Revises: bb179eae5162
Create Date: 2026-02-22 10:51:05.788456

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401
from alembic import op
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "96d18768cf0b"
down_revision: str | None = "bb179eae5162"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    statements = [
        lambda: op.drop_table("auditlog"),
        lambda: op.drop_table("paymentsconfig"),
        lambda: op.drop_constraint(
            op.f("discountcode_course_id_fkey"), "discountcode", type_="foreignkey"
        ),
        lambda: op.drop_constraint(
            op.f("fk_paymentsuser_discount_code"), "paymentsuser", type_="foreignkey"
        ),
        lambda: op.drop_constraint(
            op.f("userorganization_user_id_fkey"),
            "userorganization",
            type_="foreignkey",
        ),
        lambda: op.create_foreign_key(
            None, "userorganization", "user", ["user_id"], ["id"], ondelete="CASCADE"
        ),
        lambda: op.alter_column(
            "waitlist_config", "org_id", existing_type=sa.INTEGER(), nullable=True
        ),
        lambda: op.drop_index(
            op.f("ix_waitlist_config_launch_datetime"), table_name="waitlist_config"
        ),
        lambda: op.drop_index(
            op.f("ix_waitlist_config_org_status"), table_name="waitlist_config"
        ),
        lambda: op.drop_constraint(
            op.f("waitlist_config_waitlist_uuid_key"), "waitlist_config", type_="unique"
        ),
        lambda: op.drop_index(
            op.f("ix_waitlist_config_waitlist_uuid"), table_name="waitlist_config"
        ),
        lambda: op.create_index(
            op.f("ix_waitlist_config_waitlist_uuid"),
            "waitlist_config",
            ["waitlist_uuid"],
            unique=True,
        ),
        lambda: op.add_column(
            "waitlist_course_preference",
            sa.Column("payments_product_id", sa.Integer(), nullable=True),
        ),
        lambda: op.alter_column(
            "waitlist_course_preference",
            "user_id",
            existing_type=sa.INTEGER(),
            nullable=True,
        ),
        lambda: op.alter_column(
            "waitlist_course_preference",
            "waitlist_config_id",
            existing_type=sa.INTEGER(),
            nullable=True,
        ),
        lambda: op.alter_column(
            "waitlist_course_preference",
            "org_id",
            existing_type=sa.INTEGER(),
            nullable=True,
        ),
        lambda: op.drop_index(
            op.f("ix_wcp_course_id"), table_name="waitlist_course_preference"
        ),
        lambda: op.drop_index(
            op.f("ix_wcp_unique"), table_name="waitlist_course_preference"
        ),
        lambda: op.drop_index(
            op.f("ix_wcp_user_id"), table_name="waitlist_course_preference"
        ),
        lambda: op.drop_index(
            op.f("ix_wcp_waitlist_config_id"), table_name="waitlist_course_preference"
        ),
        lambda: op.drop_constraint(
            op.f("waitlist_course_preference_course_id_fkey"),
            "waitlist_course_preference",
            type_="foreignkey",
        ),
        lambda: op.create_foreign_key(
            None,
            "waitlist_course_preference",
            "paymentsproduct",
            ["payments_product_id"],
            ["id"],
            ondelete="CASCADE",
        ),
        lambda: op.drop_column("waitlist_course_preference", "course_id"),
        lambda: op.alter_column(
            "waitlist_email_log",
            "waitlist_config_id",
            existing_type=sa.INTEGER(),
            nullable=True,
        ),
        lambda: op.alter_column(
            "waitlist_email_log", "user_id", existing_type=sa.INTEGER(), nullable=True
        ),
        lambda: op.drop_index(
            op.f("ix_waitlist_email_log_status"), table_name="waitlist_email_log"
        ),
        lambda: op.drop_index(
            op.f("ix_waitlist_email_log_user_id"), table_name="waitlist_email_log"
        ),
        lambda: op.drop_index(
            op.f("ix_waitlist_email_log_waitlist_config_id"),
            table_name="waitlist_email_log",
        ),
        lambda: sa.Enum(
            "ACTIVE",
            "WAITLIST",
            "WAITLIST_ACTIVATED",
            "SUSPENDED",
            "PENDING_VERIFICATION",
            name="userstatusenum",
        ).drop(op.get_bind()),
        lambda: sa.Enum(
            "ACTIVE", "COMPLETED", "CANCELLED", "SCHEDULED", name="waitliststatusenum"
        ).drop(op.get_bind()),
        lambda: op.sync_enum_values(
            enum_schema="public",
            enum_name="assignmenttasktypeenum",
            new_values=["FILE_SUBMISSION", "QUIZ", "FORM", "OTHER"],
            affected_columns=[
                TableReference(
                    table_schema="public",
                    table_name="assignmenttask",
                    column_name="assignment_type",
                ),
                TableReference(
                    table_schema="public",
                    table_name="assignmenttasksubmission",
                    column_name="assignment_type",
                ),
            ],
            enum_values_to_rename=[],
        ),
        lambda: op.sync_enum_values(
            enum_schema="public",
            enum_name="paymentproviderenum",
            new_values=["paystack"],
            affected_columns=[
                TableReference(
                    table_schema="public",
                    table_name="payments_config",
                    column_name="provider",
                )
            ],
            enum_values_to_rename=[],
        ),
    ]

    for stmt in statements:
        try:
            with op.get_bind().begin_nested():
                stmt()
        except Exception:  # noqa: BLE001
            pass

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="paymentproviderenum",
        new_values=["STRIPE", "paystack"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="payments_config",
                column_name="provider",
            )
        ],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="assignmenttasktypeenum",
        new_values=["FILE_SUBMISSION", "QUIZ", "FORM", "OTHER", "CODE_EDITOR"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="assignmenttask",
                column_name="assignment_type",
            ),
            TableReference(
                table_schema="public",
                table_name="assignmenttasksubmission",
                column_name="assignment_type",
            ),
        ],
        enum_values_to_rename=[],
    )
    sa.Enum(
        "ACTIVE", "COMPLETED", "CANCELLED", "SCHEDULED", name="waitliststatusenum"
    ).create(op.get_bind())
    sa.Enum(
        "ACTIVE",
        "WAITLIST",
        "WAITLIST_ACTIVATED",
        "SUSPENDED",
        "PENDING_VERIFICATION",
        name="userstatusenum",
    ).create(op.get_bind())
    op.create_index(
        op.f("ix_waitlist_email_log_waitlist_config_id"),
        "waitlist_email_log",
        ["waitlist_config_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_waitlist_email_log_user_id"),
        "waitlist_email_log",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_waitlist_email_log_status"),
        "waitlist_email_log",
        ["email_sent"],
        unique=False,
    )
    op.alter_column(
        "waitlist_email_log", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "waitlist_email_log",
        "waitlist_config_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.add_column(
        "waitlist_course_preference",
        sa.Column("course_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "waitlist_course_preference", type_="foreignkey")
    op.create_foreign_key(
        op.f("waitlist_course_preference_course_id_fkey"),
        "waitlist_course_preference",
        "course",
        ["course_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_wcp_waitlist_config_id"),
        "waitlist_course_preference",
        ["waitlist_config_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wcp_user_id"), "waitlist_course_preference", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_wcp_unique"),
        "waitlist_course_preference",
        ["user_id", "course_id", "waitlist_config_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_wcp_course_id"),
        "waitlist_course_preference",
        ["course_id"],
        unique=False,
    )
    op.alter_column(
        "waitlist_course_preference",
        "org_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "waitlist_course_preference",
        "waitlist_config_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "waitlist_course_preference",
        "user_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.drop_column("waitlist_course_preference", "payments_product_id")
    op.drop_index(
        op.f("ix_waitlist_config_waitlist_uuid"), table_name="waitlist_config"
    )
    op.create_index(
        op.f("ix_waitlist_config_waitlist_uuid"),
        "waitlist_config",
        ["waitlist_uuid"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("waitlist_config_waitlist_uuid_key"),
        "waitlist_config",
        ["waitlist_uuid"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_waitlist_config_org_status"),
        "waitlist_config",
        ["org_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_waitlist_config_launch_datetime"),
        "waitlist_config",
        ["launch_datetime"],
        unique=False,
    )
    op.alter_column(
        "waitlist_config", "org_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_constraint(None, "userorganization", type_="foreignkey")
    op.create_foreign_key(
        op.f("userorganization_user_id_fkey"),
        "userorganization",
        "user",
        ["user_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_paymentsuser_discount_code"),
        "paymentsuser",
        "discountcode",
        ["discount_code_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("discountcode_course_id_fkey"),
        "discountcode",
        "course",
        ["course_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_table(
        "paymentsconfig",
        sa.Column("enabled", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "provider",
            postgresql.ENUM(
                "STRIPE", "paystack", name="paymentproviderenum", create_type=False
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "provider_specific_id", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "provider_config",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "creation_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "update_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organization.id"],
            name=op.f("paymentsconfig_org_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("paymentsconfig_pkey")),
    )
    op.create_table(
        "auditlog",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("org_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("action", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("resource", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("resource_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("method", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("path", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("status_code", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "payload",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("ip_address", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("auditlog_pkey")),
    )
    # ### end Alembic commands ###
