"""Add paymentsproduct table

Revision ID: 9d7156315687
Revises: 280140aa1748
Create Date: 2026-02-09 23:44:20.915499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa # noqa: F401
import sqlmodel # noqa: F401
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d7156315687'
down_revision: Union[str, None] = '280140aa1748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paymentsconfig')
    op.drop_table('auditlog')
    op.drop_constraint(op.f('paymentsproduct_payments_config_id_fkey'), 'paymentsproduct', type_='foreignkey')
    op.create_foreign_key(None, 'paymentsproduct', 'payments_config', ['payments_config_id'], ['id'], ondelete='CASCADE')
    op.add_column('paymentsuser', sa.Column('discount_code_id', sa.BigInteger(), nullable=True))
    op.add_column('paymentsuser', sa.Column('original_amount', sa.Float(), nullable=True))
    op.add_column('paymentsuser', sa.Column('discount_amount', sa.Float(), nullable=True))
    op.add_column('paymentsuser', sa.Column('final_amount', sa.Float(), nullable=True))
    op.drop_constraint(op.f('userorganization_user_id_fkey'), 'userorganization', type_='foreignkey')
    op.create_foreign_key(None, 'userorganization', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.sync_enum_values(
        enum_schema='public',
        enum_name='paymentproviderenum',
        new_values=['paystack'],
        affected_columns=[TableReference(table_schema='public', table_name='payments_config', column_name='provider')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='paymentproviderenum',
        new_values=['STRIPE', 'paystack'],
        affected_columns=[TableReference(table_schema='public', table_name='payments_config', column_name='provider')],
        enum_values_to_rename=[],
    )
    op.drop_constraint(None, 'userorganization', type_='foreignkey')
    op.create_foreign_key(op.f('userorganization_user_id_fkey'), 'userorganization', 'user', ['user_id'], ['id'])
    op.drop_column('paymentsuser', 'final_amount')
    op.drop_column('paymentsuser', 'discount_amount')
    op.drop_column('paymentsuser', 'original_amount')
    op.drop_column('paymentsuser', 'discount_code_id')
    op.drop_constraint(None, 'paymentsproduct', type_='foreignkey')
    op.create_foreign_key(op.f('paymentsproduct_payments_config_id_fkey'), 'paymentsproduct', 'paymentsconfig', ['payments_config_id'], ['id'], ondelete='CASCADE')
    op.create_table('auditlog',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resource', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('auditlog_pkey'))
    )
    op.create_table('paymentsconfig',
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('provider', postgresql.ENUM('STRIPE', 'paystack', name='paymentproviderenum', create_type=False), autoincrement=False, nullable=False),
    sa.Column('provider_specific_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('provider_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('creation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('update_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('paymentsconfig_org_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('paymentsconfig_pkey'))
    )
    # ### end Alembic commands ###
