"""add_published_to_chapter

Revision ID: a3c77189c18e
Revises: 0b7014b72e94
Create Date: 2026-05-24 22:42:23.090732

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3c77189c18e"
down_revision: str | None = "0b7014b72e94"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if not any(c["name"] == "published" for c in inspector.get_columns("chapter")):
        op.add_column(
            "chapter",
            sa.Column(
                "published",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("false"),
            ),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chapter", "published")
    # ### end Alembic commands ###
