"""add_whatsapp_group_link

Revision ID: c8e7f9a0b1c2
Revises: bdb84451a784
Create Date: 2026-07-10 15:45:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "c8e7f9a0b1c2"
down_revision: Union[str, None] = "bdb84451a784"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "course",
        sa.Column(
            "whatsapp_group_link", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("course", "whatsapp_group_link")
    # ### end Alembic commands ###
