"""Add referral system

Revision ID: d7d2e818da81
Revises: 96d18768cf0b
Create Date: 2026-02-24 00:16:18.221637

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa  # noqa: F401
import sqlmodel  # noqa: F401
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d7d2e818da81"
down_revision: Union[str, None] = "96d18768cf0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("DISPOSABLE", "LEGITIMATE", name="domainlisttype").create(op.get_bind())
    sa.Enum(
        "REQUESTED", "PROCESSING", "COMPLETED", "FAILED", name="payoutstatus"
    ).create(op.get_bind())
    sa.Enum(
        "PENDING",
        "ELIGIBLE",
        "PAID",
        "FORFEITED",
        "PENDING_REVIEW",
        name="commissionstatus",
    ).create(op.get_bind())
    sa.Enum("ACTIVE", "INACTIVE", name="referralcodestatus").create(op.get_bind())
    op.create_table(
        "emaildomainlist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "domain", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "list_type",
            postgresql.ENUM(
                "DISPOSABLE", "LEGITIMATE", name="domainlisttype", create_type=False
            ),
            nullable=False,
        ),
        sa.Column(
            "source", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_verified_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_emaildomainlist_domain"), "emaildomainlist", ["domain"], unique=False
    )
    op.create_index(
        op.f("ix_emaildomainlist_is_active"),
        "emaildomainlist",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_emaildomainlist_list_type"),
        "emaildomainlist",
        ["list_type"],
        unique=False,
    )
    op.create_table(
        "referralcode",
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column(
            "referral_link",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "ACTIVE", "INACTIVE", name="referralcodestatus", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.BigInteger(), nullable=False),
        sa.Column("referrer_user_id", sa.BigInteger(), nullable=False),
        sa.Column("creation_date", sa.DateTime(), nullable=False),
        sa.Column("update_date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["referrer_user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_referralcode_code", "referralcode", ["code"], unique=False)
    op.create_index(
        "idx_referralcode_link", "referralcode", ["referral_link"], unique=False
    )
    op.create_index(
        "idx_referralcode_referrer_org",
        "referralcode",
        ["referrer_user_id", "org_id"],
        unique=False,
    )
    op.create_index(op.f("ix_referralcode_code"), "referralcode", ["code"], unique=True)
    op.create_table(
        "referrerpayoutrequest",
        sa.Column("total_amount", sa.Float(), nullable=False),
        sa.Column(
            "currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False
        ),
        sa.Column("converted_amount", sa.Float(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "REQUESTED",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                name="payoutstatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "paystack_transfer_recipient_code",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column(
            "paystack_transfer_code",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column("bank_account_info", sa.JSON(), nullable=True),
        sa.Column("request_date", sa.DateTime(), nullable=False),
        sa.Column("completion_date", sa.DateTime(), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.BigInteger(), nullable=False),
        sa.Column("referrer_user_id", sa.BigInteger(), nullable=False),
        sa.Column("creation_date", sa.DateTime(), nullable=False),
        sa.Column("update_date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["referrer_user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_payoutrequest_org", "referrerpayoutrequest", ["org_id"], unique=False
    )
    op.create_index(
        "idx_payoutrequest_referrer_status",
        "referrerpayoutrequest",
        ["referrer_user_id", "status"],
        unique=False,
    )
    op.create_table(
        "referraltracking",
        sa.Column(
            "ip_address", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "device_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
        sa.Column("browser_fingerprint", sa.JSON(), nullable=True),
        sa.Column("registration_complete", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("referred_user_id", sa.BigInteger(), nullable=False),
        sa.Column("referral_code_id", sa.BigInteger(), nullable=False),
        sa.Column("referrer_user_id", sa.BigInteger(), nullable=False),
        sa.Column("signup_date", sa.DateTime(), nullable=False),
        sa.Column("creation_date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["referral_code_id"], ["referralcode.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["referred_user_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["referrer_user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_referraltracking_code",
        "referraltracking",
        ["referral_code_id"],
        unique=False,
    )
    op.create_index(
        "idx_referraltracking_device", "referraltracking", ["device_id"], unique=False
    )
    op.create_index(
        "idx_referraltracking_ip", "referraltracking", ["ip_address"], unique=False
    )
    op.create_index(
        "idx_referraltracking_referred",
        "referraltracking",
        ["referred_user_id"],
        unique=False,
    )
    op.create_index(
        "idx_referraltracking_unique_user",
        "referraltracking",
        ["referred_user_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_referraltracking_device_id"),
        "referraltracking",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_referraltracking_ip_address"),
        "referraltracking",
        ["ip_address"],
        unique=False,
    )
    op.create_table(
        "referralcommission",
        sa.Column("commission_amount", sa.Float(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "ELIGIBLE",
                "PAID",
                "FORFEITED",
                "PENDING_REVIEW",
                name="commissionstatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("payment_completion_date", sa.DateTime(), nullable=True),
        sa.Column("refund_period_expiration_date", sa.DateTime(), nullable=True),
        sa.Column("payout_date", sa.DateTime(), nullable=True),
        sa.Column("payout_request_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.BigInteger(), nullable=False),
        sa.Column("referrer_user_id", sa.BigInteger(), nullable=False),
        sa.Column("referred_user_id", sa.BigInteger(), nullable=False),
        sa.Column("payment_user_id", sa.BigInteger(), nullable=False),
        sa.Column("course_id", sa.BigInteger(), nullable=True),
        sa.Column("referral_code_id", sa.BigInteger(), nullable=False),
        sa.Column("creation_date", sa.DateTime(), nullable=False),
        sa.Column("update_date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["course_id"], ["course.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["payment_user_id"], ["paymentsuser.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["referral_code_id"], ["referralcode.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["referred_user_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["referrer_user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_referralcommission_org", "referralcommission", ["org_id"], unique=False
    )
    op.create_index(
        "idx_referralcommission_payment_user",
        "referralcommission",
        ["payment_user_id"],
        unique=False,
    )
    op.create_index(
        "idx_referralcommission_referred",
        "referralcommission",
        ["referred_user_id"],
        unique=False,
    )
    op.create_index(
        "idx_referralcommission_referrer_status",
        "referralcommission",
        ["referrer_user_id", "status"],
        unique=False,
    )
    op.create_index(
        "idx_referralcommission_unique",
        "referralcommission",
        ["payment_user_id", "referral_code_id"],
        unique=True,
    )
    op.drop_table("auditlog")
    op.add_column(
        "paymentsuser", sa.Column("referral_code_id", sa.BigInteger(), nullable=True)
    )
    op.drop_constraint(
        op.f("fk_paymentsuser_discount_code_id"), "paymentsuser", type_="foreignkey"
    )
    op.add_column(
        "user",
        sa.Column(
            "referral_commission_balance",
            sa.Float(),
            nullable=False,
            server_default="0.0",
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "has_referral_code", sa.Boolean(), nullable=False, server_default="false"
        ),
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="assignmenttasktypeenum",
        new_values=["FILE_SUBMISSION", "QUIZ", "FORM", "OTHER", "CODE_EDITOR"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="assignmenttask",
                column_name="assignment_type",
            ),
            TableReference(
                table_schema="public",
                table_name="assignmenttasksubmission",
                column_name="assignment_type",
            ),
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="assignmenttasktypeenum",
        new_values=["FILE_SUBMISSION", "QUIZ", "FORM", "OTHER", "CODE_EDITOR"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="assignmenttask",
                column_name="assignment_type",
            ),
            TableReference(
                table_schema="public",
                table_name="assignmenttasksubmission",
                column_name="assignment_type",
            ),
        ],
        enum_values_to_rename=[],
    )
    op.drop_column("user", "has_referral_code")
    op.drop_column("user", "referral_commission_balance")
    op.create_foreign_key(
        op.f("fk_paymentsuser_discount_code_id"),
        "paymentsuser",
        "discountcode",
        ["discount_code_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("paymentsuser", "referral_code_id")
    op.create_table(
        "auditlog",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("org_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("action", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("resource", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("resource_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("method", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("path", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("status_code", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "payload",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("ip_address", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("auditlog_pkey")),
    )
    op.drop_index("idx_referralcommission_unique", table_name="referralcommission")
    op.drop_index(
        "idx_referralcommission_referrer_status", table_name="referralcommission"
    )
    op.drop_index("idx_referralcommission_referred", table_name="referralcommission")
    op.drop_index(
        "idx_referralcommission_payment_user", table_name="referralcommission"
    )
    op.drop_index("idx_referralcommission_org", table_name="referralcommission")
    op.drop_table("referralcommission")
    op.drop_index(op.f("ix_referraltracking_ip_address"), table_name="referraltracking")
    op.drop_index(op.f("ix_referraltracking_device_id"), table_name="referraltracking")
    op.drop_index("idx_referraltracking_unique_user", table_name="referraltracking")
    op.drop_index("idx_referraltracking_referred", table_name="referraltracking")
    op.drop_index("idx_referraltracking_ip", table_name="referraltracking")
    op.drop_index("idx_referraltracking_device", table_name="referraltracking")
    op.drop_index("idx_referraltracking_code", table_name="referraltracking")
    op.drop_table("referraltracking")
    op.drop_index(
        "idx_payoutrequest_referrer_status", table_name="referrerpayoutrequest"
    )
    op.drop_index("idx_payoutrequest_org", table_name="referrerpayoutrequest")
    op.drop_table("referrerpayoutrequest")
    op.drop_index(op.f("ix_referralcode_code"), table_name="referralcode")
    op.drop_index("idx_referralcode_referrer_org", table_name="referralcode")
    op.drop_index("idx_referralcode_link", table_name="referralcode")
    op.drop_index("idx_referralcode_code", table_name="referralcode")
    op.drop_table("referralcode")
    op.drop_index(op.f("ix_emaildomainlist_list_type"), table_name="emaildomainlist")
    op.drop_index(op.f("ix_emaildomainlist_is_active"), table_name="emaildomainlist")
    op.drop_index(op.f("ix_emaildomainlist_domain"), table_name="emaildomainlist")
    op.drop_table("emaildomainlist")
    sa.Enum("ACTIVE", "INACTIVE", name="referralcodestatus").drop(op.get_bind())
    sa.Enum(
        "PENDING",
        "ELIGIBLE",
        "PAID",
        "FORFEITED",
        "PENDING_REVIEW",
        name="commissionstatus",
    ).drop(op.get_bind())
    sa.Enum("REQUESTED", "PROCESSING", "COMPLETED", "FAILED", name="payoutstatus").drop(
        op.get_bind()
    )
    sa.Enum("DISPOSABLE", "LEGITIMATE", name="domainlisttype").drop(op.get_bind())
    # ### end Alembic commands ###
