"""Initial Migration

Revision ID: df2981bf24dd
Revises: 
Create Date: 2024-07-11 19:33:37.993767

"""
from typing import Sequence, Union

from alembic import op
from grpc import server # noqa: F401
import sqlalchemy as sa
import sqlmodel # noqa: F401
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'df2981bf24dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def table_exists(table_name: str, conn) -> bool:
    """Check if a table exists."""
    inspector = inspect(conn)
    return table_name in inspector.get_table_names()


def column_exists(table_name: str, column_name: str, conn) -> bool:
    """Check if a column exists in a table."""
    if not table_exists(table_name, conn):
        return False
    inspector = inspect(conn)
    try:
        columns = [col['name'] for col in inspector.get_columns(table_name)]
        return column_name in columns
    except Exception:
        return False


def constraint_exists(table_name: str, constraint_name: str, conn) -> bool:
    """Check if a constraint exists in a table."""
    inspector = inspect(conn)
    try:
        constraints = [c['name'] for c in inspector.get_unique_constraints(table_name)]
    except Exception:
        constraints = []
    
    try:
        fks = [fk['name'] for fk in inspector.get_foreign_keys(table_name)]
    except Exception:
        fks = []
    
    try:
        pk_constraint = inspector.get_pk_constraint(table_name)
        pks = [pk_constraint['name']] if pk_constraint.get('name') else []
    except Exception:
        pks = []
    
    all_constraints = constraints + fks + pks
    return constraint_name in all_constraints


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    
    # Add 'published' column if it doesn't exist
    if table_exists('activity', conn) and not column_exists('activity', 'published', conn):
        op.add_column('activity', sa.Column('published', sa.Boolean(), nullable=False, server_default=sa.true()))
    
    # Drop 'published_version' column if it exists
    if table_exists('activity', conn) and column_exists('activity', 'published_version', conn):
        op.drop_column('activity', 'published_version')
    
    # Drop 'version' column if it exists
    if table_exists('activity', conn) and column_exists('activity', 'version', conn):
        op.drop_column('activity', 'version')
    
    # Drop 'assignment_user_uuid' column if it exists
    if table_exists('assignmentusersubmission', conn) and column_exists('assignmentusersubmission', 'assignment_user_uuid', conn):
        op.drop_column('assignmentusersubmission', 'assignment_user_uuid')

    # Update foreign key constraints - drop if exists, then create
    # Handle trail_org_id_fkey
    if table_exists('trail', conn):
        inspector = inspect(conn)
        try:
            fks = inspector.get_foreign_keys('trail')
            for fk in fks:
                if 'org_id' in fk['constrained_columns']:
                    try:
                        op.drop_constraint(fk['name'], 'trail', type_='foreignkey')
                    except Exception:
                        pass  # Constraint might have different name or already dropped
                    break
        except Exception:
            pass  # No foreign keys found
        
        try:
            op.create_foreign_key('trail_org_id_fkey', 'trail', 'organization', ['org_id'], ['id'], ondelete='CASCADE')
        except Exception as e:
            error_msg = str(e).lower()
            if 'already exists' not in error_msg and 'duplicate' not in error_msg:
                raise  # Re-raise if it's a different error
        
        # Handle trail_user_id_fkey
        try:
            fks = inspector.get_foreign_keys('trail')
            for fk in fks:
                if 'user_id' in fk['constrained_columns']:
                    try:
                        op.drop_constraint(fk['name'], 'trail', type_='foreignkey')
                    except Exception:
                        pass  # Constraint might have different name or already dropped
                    break
        except Exception:
            pass  # No foreign keys found
        
        try:
            op.create_foreign_key('trail_user_id_fkey', 'trail', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        except Exception as e:
            error_msg = str(e).lower()
            if 'already exists' not in error_msg and 'duplicate' not in error_msg:
                raise  # Re-raise if it's a different error
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('trail_org_id_fkey', 'trail', type_='foreignkey')
    op.create_foreign_key('trail_org_id_fkey', 'trail', 'organization', ['org_id'], ['id'])
    op.drop_constraint('trail_user_id_fkey', 'trail', type_='foreignkey')
    op.create_foreign_key('trail_user_id_fkey', 'trail', 'user', ['user_id'], ['id'])

    op.add_column('assignmentusersubmission', sa.Column('assignment_user_uuid', sa.VARCHAR(), autoincrement=False, nullable=False))

    op.add_column('activity', sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False, server_default=sa.text('1')))
    op.add_column('activity', sa.Column('published_version', sa.INTEGER(), autoincrement=False, nullable=False, server_default=sa.text('1')))
    op.drop_column('activity', 'published')
    # ### end Alembic commands ###

