"""Org Scripts

Revision ID: eb10d15465b3
Revises: a5afa69dd917
Create Date: 2025-06-08 18:12:18.853988

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa  # noqa: F401
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "eb10d15465b3"
down_revision: Union[str, None] = "a5afa69dd917"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    org_columns = [c["name"] for c in inspector.get_columns("organization")]
    if "scripts" not in org_columns:
        op.add_column("organization", sa.Column("scripts", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization", "scripts")
    # ### end Alembic commands ###
