"""
Referral Code database models
Stores permanent referral codes generated by users
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Optional

from sqlalchemy import func
from sqlmodel import BigInteger, Column, Field, ForeignKey, Index, SQLModel


class ReferralCodeStatus(str, Enum):
    """Status of referral code"""

    ACTIVE = "active"
    INACTIVE = "inactive"


class ReferralCodeBase(SQLModel):
    """Base model for referral codes"""

    code: str = Field(max_length=50, sa_column_kwargs={"unique": True}, index=True)
    referral_link: str = Field(max_length=255)
    status: ReferralCodeStatus = Field(default=ReferralCodeStatus.ACTIVE)


class ReferralCode(ReferralCodeBase, table=True):
    """Referral code table - permanent codes for users"""

    __tablename__ = "referralcode"
    __table_args__ = (
        Index("idx_referralcode_referrer_org", "referrer_user_id", "org_id"),
        Index("idx_referralcode_code", "code"),
        Index("idx_referralcode_link", "referral_link"),
    )

    id: Optional[int] = Field(default=None, primary_key=True)
    org_id: int = Field(
        sa_column=Column(
            BigInteger,
            ForeignKey("organization.id", ondelete="CASCADE"),
            nullable=False,
        )
    )
    referrer_user_id: int = Field(
        sa_column=Column(
            BigInteger, ForeignKey("user.id", ondelete="CASCADE"), nullable=False
        )
    )
    creation_date: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Creation timestamp in UTC",
    )
    update_date: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        sa_column_kwargs={"onupdate": func.now()},
        description="Last update timestamp in UTC (auto-refreshed by DB)",
    )


class ReferralCodeRead(ReferralCodeBase):
    """Response model for referral codes"""

    id: int
    org_id: int
    referrer_user_id: int
    creation_date: datetime
    update_date: datetime


class ReferralCodeCreate(SQLModel):
    """Model for creating referral code"""

    org_id: int


class ReferralCodeUpdate(SQLModel):
    """Model for updating referral code status"""

    status: ReferralCodeStatus
